### ISSUE TITLE
`Error: null pointer passed to rust` when building writing properties

### ISSUE THREAD

**Issue by belopash** [kylebarron/parquet-wasm#256]
When I try to build writing properties with the following code, I get `Error: null pointer passed to rust`
```
let builder = new WriterPropertiesBuilder()
builder.setCompression(Compression.SNAPPY)) // can be any method
builder.setDictionaryEnabled(true) // can be any method
```

```
C:\Users\abelo\test\common\temp\node_modules\.pnpm\parquet-wasm@0.4.0-beta.5\node_modules\parquet-wasm\node\arrow1.js:647
    throw new Error(getStringFromWasm0(arg0, arg1));
    ^

Error: null pointer passed to rust
    at module.exports.__wbindgen_throw (C:\Users\abelo\test\common\temp\node_modules\.pnpm\parquet-wasm@0.4.0-beta.5\node_modules\parquet-wasm\node\arrow1.js:647:11)
    at wasm://wasm/00fe6a1a:wasm-function[6036]:0x320658
    at wasm://wasm/00fe6a1a:wasm-function[4734]:0x311c9b
    at wasm://wasm/00fe6a1a:wasm-function[4439]:0x30b0ff
    at WriterPropertiesBuilder.setDictionaryEnabled (C:\Users\abelo\test\common\temp\node_modules\.pnpm\parquet-wasm@0.4.0-beta.5\node_modules\parquet-wasm\node\arrow1.js:498:26)
```

However, if you change the code in this way, the problem disappears
```
let builder = new WriterPropertiesBuilder().setCompression(0).setDictionaryEnabled(true)
```

I'm using `parquet-wasm@0.4.0-beta.5`

**Comment by kylebarron** [comment]
That is correct, the builder API returns a new object and doesn't mutate the previous one, so in the first case you'd need to overwrite the builder variable

**Comment by belopash** [comment]
Thanks, it works now
```
let builder = new WriterPropertiesBuilder()
builder = builder.setCompression(0)
builder = builder.setDictionaryEnabled(true)
```
