### ISSUE TITLE
Having problem running on AWS Lambda .

### ISSUE THREAD

**Issue by muratorema** [kylebarron/parquet-wasm#590]
Package.json:
```json
{
  "name": "mx-data-transfer",
  "version": "1.0.0",
  "description": "hello world sample for NodeJS",
  "main": "index.js",
  "repository": "https://github.com/awslabs/aws-sam-cli/tree/develop/samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs",
  "author": "SAM CLI",
  "license": "MIT",
  "scripts": {
    "unit": "jest",
    "lint": "eslint '*.ts' --quiet --fix",
    "compile": "tsc",
    "test": "npm run compile && npm run unit",
    "prebuild": "rm -rf dist",
    "build": "esbuild index.ts --bundle --minify --sourcemap --platform=node --target=es2022 --outfile=dist/index.js",
    "wasmBuild": "cp node_modules/parquet-wasm/bundler/parquet_wasm_bg.wasm dist/parquet_wasm_bg.wasm",
    "postbuild": "npm run wasmBuild && cd dist && zip -r index.zip index.js* parquet_wasm_bg.wasm*"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.637.0",
    "apache-arrow": "^17.0.0",
    "esbuild": "^0.14.14",
    "parquet-wasm": "^0.6.1"
  },
  "devDependencies": {
    "@jest/globals": "29.7.0",
    "@types/aws-lambda": "^8.10.92",
    "@types/jest": "29.5.12",
    "@types/node": "^18.11.4",
    "@typescript-eslint/eslint-plugin": "^5.10.2",
    "@typescript-eslint/parser": "^5.10.2",
    "eslint": "^8.8.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.7.0",
    "prettier": "^2.5.1",
    "ts-jest": "^29.2.5",
    "ts-node": "^10.9.2",
    "typescript": "5.5.4"
  }
}

```

AWS Lambda Error:
```
{
    "errorType": "TypeError",
    "errorMessage": "WebAssembly.Instance(): Import #0 module=\"./parquet_wasm_bg.js\" error: module is not an object or function",
    "stack": [
        "TypeError: WebAssembly.Instance(): Import #0 module=\"./parquet_wasm_bg.js\" error: module is not an object or function",
        "    at /var/task/index.js:2:37751",
        "    at /var/task/index.js:1:222",
        "    at Object.<anonymous> (/var/task/index.js:66:48286)",
        "    at Module._compile (node:internal/modules/cjs/loader:1358:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1208:32)",
        "    at Module._load (node:internal/modules/cjs/loader:1024:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1233:19)",
        "    at require (node:internal/modules/helpers:179:18)",
        "    at _tryRequireFile (file:///var/runtime/index.mjs:1002:37)"
    ]
}
```

I stuck

Have I missed a configuration in package.json to use parquet-wasm? By the way  parquet-wasm works in unit  test perfectly.

**Comment by kylebarron** [comment]
I've never tried to use it in Lambda. What is your code?

**Comment by muratorema** [comment]
@kylebarron  Thank you replay.

I have created an sample project with the same configuration I have problem.

You can clone github.com:muratorema/parquet-wasm-missing-conf-or-bug.git repo and you can get the same error.

```sh
mo@MetaMac goo % git clone git@github.com:muratorema/parquet-wasm-missing-conf-or-bug.git --depth 1
Cloning into 'parquet-wasm-missing-conf-or-bug'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 15 (delta 0), reused 13 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (15/15), 64.42 KiB | 622.00 KiB/s, done.
mo@MetaMac goo % ls
parquet-wasm-missing-conf-or-bug
mo@MetaMac goo % cd parquet-wasm-missing-conf-or-bug 
mo@MetaMac parquet-wasm-missing-conf-or-bug % ls
README.md	sample_app
mo@MetaMac parquet-wasm-missing-conf-or-bug % cd sample_app 
mo@MetaMac sample_app % node --version
v21.7.3
mo@MetaMac sample_app % npm install
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead

added 616 packages, and audited 617 packages in 2s

62 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
mo@MetaMac sample_app % npm run build

> mx-data-transform@1.0.0 prebuild
> rm -rf dist


> mx-data-transform@1.0.0 build
> esbuild index.ts --bundle --minify --sourcemap --platform=node --target=es2022 --outfile=dist/index.js


  dist/index.js      247.2kb
  dist/index.js.map  523.5kb

⚡ Done in 15ms

> mx-data-transform@1.0.0 postbuild
> cd dist && zip -r index.zip index.js* parquet_wasm_bg.wasm*

	zip warning: name not matched: parquet_wasm_bg.wasm*
  adding: index.js (deflated 77%)
  adding: index.js.map (deflated 78%)
mo@MetaMac sample_app % cd dist 
mo@MetaMac dist % node index.js
node:fs:580
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open '/private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/parquet_wasm_bg.wasm'
    at Object.openSync (node:fs:580:18)
    at Object.readFileSync (node:fs:459:35)
    at /private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:2:37625
    at /private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:1:223
    at Object.<anonymous> (/private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:11:48167)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/parquet_wasm_bg.wasm'
}

Node.js v21.7.3
mo@MetaMac dist % cp ../node_modules/parquet-wasm/node/parquet_wasm_bg.wasm .
mo@MetaMac dist % node index.js                                              
/private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:11

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

TypeError: (0 , pe.default) is not a function
    at a_ (/private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:11:48212)
    at Object.<anonymous> (/private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:11:48626)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49

Node.js v21.7.3
mo@MetaMac dist % cp ../node_modules/parquet-wasm/esm/parquet_wasm_bg.wasm . 
mo@MetaMac dist % node index.js                                             
/private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:2

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

TypeError: WebAssembly.Instance(): Import #0 module="wbg": module is not an object or function
    at /private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:2:37675
    at /private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:1:223
    at Object.<anonymous> (/private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:11:48167)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49

Node.js v21.7.3
mo@MetaMac dist % cp ../node_modules/parquet-wasm/esm/parquet_wasm_bg.wasm .
mo@MetaMac dist % cp ../node_modules/parquet-wasm/bundler/parquet_wasm_bg.wasm .
mo@MetaMac dist % node index.js                                                 
/private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:2

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

TypeError: WebAssembly.Instance(): Import #0 module="./parquet_wasm_bg.js": module is not an object or function
    at /private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:2:37675
    at /private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:1:223
    at Object.<anonymous> (/private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:11:48167)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49

Node.js v21.7.3
mo@MetaMac dist % cp ../node_modules/parquet-wasm/bundler/parquet_wasm_bg.js .
mo@MetaMac dist % node index.js                                               
/private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:2

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

TypeError: WebAssembly.Instance(): Import #0 module="./parquet_wasm_bg.js": module is not an object or function
    at /private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:2:37675
    at /private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:1:223
    at Object.<anonymous> (/private/tmp/goo/parquet-wasm-missing-conf-or-bug/sample_app/dist/index.js:11:48167)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49

Node.js v21.7.3
mo@MetaMac dist % 


```

**Comment by kylebarron** [comment]
> zip warning: name not matched: parquet_wasm_bg.wasm*

you probably need to ensure you're including that file. you also should ensure you're using the node distribution of the library. Given that it works in node it should have no problem in lambda as long as it's packaged correctly
